{% set name = "udlai" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f90052f0c9f5819df3f46b9fc701e58b2228c6e09a0c28418b3f5971b39df7e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - requests

test:
  imports:
    - udlai

about:
  home: http://udlai.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: UDL.AI Python interface
  description: |
    `udlai` is a way of interacting with the UDL.AI platform for location
    intelligence using a convenient Python API.
  doc_url: http://udlai.readthedocs.org
  dev_url: https://github.com/udl-ai/udlai

extra:
  recipe-maintainers:
    - martinfleis
