{% set name = "udlai" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27745c6189ed4b14ed7359954fb89e12c30cd41631f87a4c56d25e54330b2522

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - pandas
    - requests

test:
  imports:
    - udlai

about:
  home: http://udlai.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: UDL.AI Python interface
  description: |
    `udlai` is a way of interacting with the UDL.AI platform for location
    intelligence using a convenient Python API.
  doc_url: http://udlai.readthedocs.org
  dev_url: https://github.com/udl-ai/udlai

extra:
  recipe-maintainers:
    - martinfleis
